version: "3"

services:
      
  webapp:
    build: .
    restart: always
    env_file:
      - .ENV
    ports:
      - "8080:8080"
    networks:
      - spring-boot-petclinic
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    env_file:
      - .ENV
    ports:
      - "3306:3306"
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    networks:
      - spring-boot-petclinic

networks:
  spring-boot-petclinic: